spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/icount
    username: icountdev
    password: 1q2w3e4r

  data:
    redis:
      port: 26379
      host: 127.0.0.1

logging:
  level:
    root: debug