server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: always
      encoding: UTF-8
  datasource:
    sql-script-encoding: UTF-8

cors:
  allowed-origins: '*'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
