version: '3'
services:
  mysql-icount:
    image: mysql:8.0
    container_name: mysql-icount
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: icountdev
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: icount

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - icount-mysql-volume:/var/lib/mysql

volumes:
  icount-mysql-volume:
    driver: local